### ISSUE TITLE
goto menu on mobile devices

### ISSUE THREAD

**Issue by jozsefk9** [imakewebthings/deck.js#169]
I can't figure out how to get the goto menu appear if I load the presentation on smartphone for example?

**Comment by imakewebthings** [comment]
The extension does not provide a default user interaction to bring the Goto menu up on mobile. However, if you want to write your own interaction (say a button that only shows on touch devices) you can call the [goTo methods](http://imakewebthings.com/deck.js/docs/#deck-goto-methods) to hide/show/toggle.
