### ISSUE TITLE
Setup deck.js on cdn?

### ISSUE THREAD

**Issue by PeterDaveHello** [imakewebthings/deck.js#170]
Hi @imakewebthings,

I'm Peter from https://github.com/cdnjs/cdnjs, the largest open source public cdn service,

I would like to add this awesome project on cdnjs,

would you please help me confirm that the file list we needed?

I think it should be like this

```
core\*.css
extensions\*\*.js
themes\*\*.css
```

Thanks.

**Comment by imakewebthings** [comment]
You also need core JS and extension CSS:

```
core\*.js
extensions\*\*.css
```

**Comment by PeterDaveHello** [comment]
Okay, thanks.

**Comment by PeterDaveHello** [comment]
Added here https://cdnjs.com/libraries/deck.js
