### ISSUE TITLE
Space bar and Backspace keys work like Left and Right

### ISSUE THREAD

**Issue by r-gaia-cs** [imakewebthings/deck.js#179]
I want to add it because based on https://github.com/swcarpentry/slideshows/pull/22.

This should not be difficult to implement taking  https://github.com/imakewebthings/deck.js/pull/43. as starting point.

**Comment by imakewebthings** [comment]
@r-gaia-cs The "next" keys already default to Enter, Space, Right, Down, and PageDown, and the "previous" keys default to Backspace, Left, Up, and PageUp. Are you seeing something different?

**Comment by r-gaia-cs** [comment]
@imakewebthings Thanks for the feedback. The slides that I got was using a old version. Sorry to the trouble.
