### ISSUE TITLE
Sample doesn't work

### ISSUE THREAD

**Issue by jcoyne** [imakewebthings/deck.js#184]
This presentation doesn't advance:
http://imakewebthings.com/deck.js/introduction/

Using Firefox 38.0.5 on mac.

**Comment by ErichHartmann** [comment]
There is no issue here. The form you linked to doesn't have focus on the presentation when in loads. You are hitting the keys to advance, but the pull-down controls are in focus. Try clicking on the presentation and then the advance and rewind controls wore fine.
