### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [imakewebthings/deck.js#206]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by copernico** [comment]
I'm also interested to know; I am considering basing a project of mine on deck.js, but I'm hesitating....

**Comment by DanielRuf** [comment]
I would say it is not actively maintained anymore. There is revealjs and a few more which are also listed in the readme at https://github.com/astefanutti/decktape

I still use revealjs because it is widely used and actively maintained.
