### ISSUE TITLE
understanding deck.js demo (http://imakewebthings.github.com/deck.js/)

### ISSUE THREAD

**Issue by rinaldi6109** [imakewebthings/deck.js#66]
I discoveded deck.js some days ago and I was fascinated by it.
I read carefully deck.js html source (or, at least, I think so). 
Unfortunately, I was not able to understand how the transition from one slide to another occours.
For example, how go from http://imakewebthings.github.com/deck.js/#slides-html slide to http://imakewebthings.github.com/deck.js/#slide-states slide?
The two successive slides are identified by two different ids in html source code (slide-html and slide-states) but I miss how text is placed or hidden (or colored!) to the screen according to them. I suppose that somewhere there is a (ordered) list of ids which defines transition between slides with the help of a css file, but I'm not sure...
Can you help me?
Thank you.

**Comment by cksachdev** [comment]
I am looking for a presentation solution where I could explain large json structures and showing and highlighting pieces of json is a good way. Is there any alternative or better solution to achieve this or can deck.js be used to achieve this
@imakewebthings @rinaldi6109 @vaibhavbhuva
