### ISSUE TITLE
adding header and footer

### ISSUE THREAD

**Issue by marianghela** [imakewebthings/deck.js#85]
Hello!
I am trying to understand deck.js and how to design my own theme.
I'd like to design a page with header and footer (like http://imakewebthings.com/deck.js/).
To do that, i need to include all the `<section>` tags inside an `<article>` or a generic div. But when I do that, the page doesn't work anymore (the arrows disappear and the slide movement too!)
Anyone can help me?

Thanks a lot
Mari

**Comment by mduaneh** [comment]
I'm css newbie, but I need to add a header and footer as well.  The example @marianghela put up is no longer available.  I use the asciidoctor to deckjs workflow, but right now I'm just trying to understand how to add some branding to all slides.
Would it be possible to describe how this would work?

I can see the footer (not shown) but have to scroll down past the slides add on.

Currently I have something like below:
<body class="WIRE">
<header>
<h1>I am A Header</h1>
</header>
<div class="deck-container">
<section class="slide" id="title-slide">
